services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    init: true
    stop_grace_period: 30s
    networks:
      - dokploy-network
    labels:
      traefik.enable: "true"
      traefik.docker.network: dokploy-network

      traefik.http.routers.acs-group-http.rule: Host(`acs.atcchinabrasil.com`)
      traefik.http.routers.acs-group-http.entrypoints: web
      traefik.http.routers.acs-group-http.middlewares: acs-group-https-redirect
      traefik.http.routers.acs-group-http.service: acs-group
      traefik.http.middlewares.acs-group-https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.acs-group-https-redirect.redirectscheme.permanent: "true"

      traefik.http.routers.acs-group-https.rule: Host(`acs.atcchinabrasil.com`)
      traefik.http.routers.acs-group-https.entrypoints: websecure
      traefik.http.routers.acs-group-https.tls: "true"
      traefik.http.routers.acs-group-https.tls.certresolver: letsencrypt
      traefik.http.routers.acs-group-https.service: acs-group
      traefik.http.services.acs-group.loadbalancer.server.port: "3000"

networks:
  dokploy-network:
    external: true
