"""Generate the local SVG from Natural Earth 1:110m countries (public domain).

Usage: python3 scripts/generate-trade-map.py /path/to/ne_110m_admin_0_countries.geojson
See docs/show-map.md for the pinned source and projection.
"""

import json
from pathlib import Path
import sys
from xml.sax.saxutils import quoteattr


def project(point):
    longitude, latitude = point[:2]
    return f"{(longitude + 180) * 4:.1f},{(85 - latitude) * 4:.1f}"


def generate(source):
    features = json.loads(Path(source).read_text())["features"]
    paths = []
    for feature in features:
        code = feature["properties"]["ADM0_A3"]
        if code == "ATA":
            continue
        geometry = feature["geometry"]
        polygons = geometry["coordinates"]
        if geometry["type"] == "Polygon":
            polygons = [polygons]
        elif geometry["type"] != "MultiPolygon":
            raise ValueError(f"Unsupported geometry: {geometry['type']}")
        data = "".join(
            "M" + "L".join(project(point) for point in ring) + "Z"
            for polygon in polygons
            for ring in polygon
        )
        highlight = ' fill="#123e48" stroke="#357981"' if code in {"BRA", "CHN"} else ""
        paths.append(f'<path data-country={quoteattr(code)} d="{data}"{highlight}/>')

    output = Path(__file__).resolve().parents[1] / "public/maps/world-countries.svg"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 600">\n'
        '<!-- Natural Earth v5.1.2, public domain. Generated by scripts/generate-trade-map.py. -->\n'
        '<g fill="#142a3a" stroke="#2b4557" stroke-width="0.7" stroke-linejoin="round" fill-rule="evenodd">\n'
        + "\n".join(paths)
        + "\n</g></svg>\n"
    )
    print(f"Generated {output.name}: {len(paths)} countries, {output.stat().st_size:,} bytes")


if __name__ == "__main__":
    generate(sys.argv[1])
